### ISSUE TITLE
Does not compile with latest async-std and additional compilation errors

### ISSUE THREAD

**Issue by ethindp** [async-rs/parallel-stream#22]
This crate does not compile with the latest version of async-std (v. 1.10.0). I'd fix it but am unsure what I'll break, so I'm filing it as an issue here before I file a PR. Specifically, the following changes have been made in async-std 1.10.0 that break the crate:

* `sync::Receiver` and `sync::Sender` have been moved to the `channel` module.

Furthermore, `par_stream/map.rs` defines `Map<T>`, but parameter `T` is never used (error E0392).

Compiling with rustc 1.57.0-nightly (2c7bc5e33 2021-09-15).

**Comment by yoshuawuyts** [comment]
published a new version which fixes this!
